# Site settings
title: Eric Carlisle
email: eric@ericcarlisle.com
description: > # this means to ignore newlines until "baseurl:"
  Eric has 20 years of experience in full-stack website development, with a passion for user interface development and user experience design.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.ericcarlisle.com" # the base hostname & protocol for your site
twitter_username: eric_carlisle
github_username:  ecarlisle

# Build settings
markdown: kramdown

# Outputting
permalink: pretty
highlighter: pygments
sass:
    sass_dir: _sass
    style: :expanded